version = 1

exclude_patterns = [
  "    \"Application/**\",",
  "    \"Custom/**\",",
  "    \"Datasheet/**\",",
  "    \"Picture/**\",",
  "    \"Code/Client/**\",",
  "    \"Code/Libs/**\",",
  "    \"*.md\",",
  "    \"*.pdf\",",
  "    \"*.exe\""
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"