version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

  [analyzers.config]
  root = "Code/Server"
  exclude_patterns = [
    "../../Application/**",
    "../../Custom/**",
    "../../Datasheet/**",
    "../../Picture/**",
    "../../Code/Client/**",
    "../../Code/Libs/**"
  ]