# Type stub for flask (Web framework)
from typing import Any, Dict, Optional, Callable

class Request:
    method: str
    json: Any
    def get_json(self) -> Any: ...

class Flask:
    config: Dict[str, Any]
    jinja_env: Any
    robot_state: Any
    
    def __init__(self, import_name: str, **kwargs: Any) -> None: ...
    def route(self, rule: str, **options: Any) -> Callable: ...
    def run(self, host: Optional[str] = None, port: Optional[int] = None, debug: bool = False, **kwargs: Any) -> None: ...
    def add_url_rule(self, rule: str, endpoint: Optional[str] = None, view_func: Optional[Callable] = None, **options: Any) -> None: ...
    def errorhandler(self, code_or_exception: Any) -> Callable: ...

request: Request
def jsonify(*args: Any, **kwargs: Any) -> Any: ...
def render_template(template_name: str, **context: Any) -> str: ...
def current_app() -> Flask: ...