# Type stub for gpiozero (GPIO control)
from typing import Optional

class OutputDevice:
    def __init__(self, pin: int, active_high: bool = True, initial_value: bool = False) -> None: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def toggle(self) -> None: ...
    @property
    def value(self) -> float: ...
    @value.setter
    def value(self, value: float) -> None: ...

class DistanceSensor:
    def __init__(self, echo: int, trigger: int, max_distance: float = 1.0) -> None: ...
    @property 
    def distance(self) -> float: ...

class DistanceSensorNoEcho:
    def __init__(self, pin: int, max_distance: float = 1.0) -> None: ...
    @property
    def distance(self) -> float: ...

class PWMSoftwareFallback:
    pass