# Type stub for smbus (I2C communication)
class SMBus:
    def __init__(self, bus: int = 1) -> None: ...
    def read_byte(self, addr: int) -> int: ...
    def read_byte_data(self, addr: int, cmd: int) -> int: ...
    def read_word_data(self, addr: int, cmd: int) -> int: ...
    def write_byte(self, addr: int, val: int) -> None: ...
    def write_byte_data(self, addr: int, cmd: int, val: int) -> None: ...
    def write_word_data(self, addr: int, cmd: int, val: int) -> None: ...
    def close(self) -> None: ...